version: '3'
services:
  nginx:
    image: nginx:1.15.7-alpine
    depends_on:
      - pycon_backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  pycon_backend:
    build: backend
    depends_on:
      - pycon_database
    volumes:
      - ${PYCON_BACKEND_ENV}:/app/.env:ro
  pycon_database:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_USER=pycon
      - POSTGRES_DB=pycon
