version: '3'
services:
  nginx:
    build: nginx
    depends_on:
      - pycon_backend
    volumes:
      - static-sites:/var/sites/:ro
  pycon_backend:
    build: backend
    depends_on:
      - pycon_database
    volumes:
      - ${PYCON_BACKEND_ENV}:/app/.env:ro
  pycon_database:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_USER=pycon
      - POSTGRES_DB=pycon
  pycon_frontend:
    build: frontend
    volumes:
      - static-sites:/sites/

volumes:
  static-sites:
